name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Pragma
        shell: bash
        run: |
          git clone https://github.com/Silverlan/pragma.git --recurse-submodules
          cp linux/pragma_build_linux.sh pragma/build_scripts/build_linux.sh
          cd pragma
          bash ./build_scripts/build_linux.sh
          
      - name: Handle Error
        uses: Silverlan/common_actions/action_handle_error@main
        if: failure()
        
